#!/bin/sh

# This script will mount a squashfs partition to /run/eupnea and setup an overlay fs to set as the new root.

WORKING_DIR="/run/eupnea"
SFS_DIR=$WORKING_DIR/sfs
TMP_DIR=$WORKING_DIR/tmp
# Device is hardcoded to /dev/sda for now
DEVICE="/dev/sda"

mkdir -p $SFS_DIR
mkdir -p $TMP_DIR

# Mount the squashfs partition
mount "$DEVICE"3 $SFS_DIR
